Fio domain registration
EdgeApp/edge-react-gui pull request #2117
Opened 2020-08-12 12:16 UTC by andreyvEze

2020-08-28 17:59 UTC, andreyvEze commented on src/components/scenes/FioNameConfirmScene.js
> +const styles: typeof rawStyles = StyleSheet.create(rawStyles)
change to be THEMEd, transaction details like as example

2020-09-02 16:32 UTC, andreyvEze commented on ios/Podfile.lock
> +COCOAPODS: 1.10.0.beta.2
remove

2020-09-02 16:37 UTC, andreyvEze commented on src/components/scenes/FioAddressListScene.js
> +    paddingHorizontal: scale(10)
THEME.rem

2020-09-02 16:39 UTC, andreyvEze commented on src/components/scenes/FioAddressRegisterScene.js
> +  iconIon: {
remove it

2020-09-02 16:39 UTC, andreyvEze commented on src/components/scenes/FioAddressRegisterSelectWalletScene.js
> +  iconIon: {
remove

2020-09-02 16:45 UTC, andreyvEze commented on src/components/scenes/FioDomainRegisterScene.js
> +const ionIconSize = THEME.rem(4)
remove, use from { theme } = this.props

2020-09-02 16:56 UTC, andreyvEze commented on src/components/scenes/FioDomainRegisterScene.js
> +            <IonIcon name="ios-at" style={styles.iconIon} color={THEME.COLORS.BLUE_3} size={ionIconSize} />
theme from props

2020-09-02 16:56 UTC, andreyvEze commented on src/components/scenes/FioDomainRegisterScene.js
> +                  selectionColor={THEME.COLORS.ACCENT_MINT}
use from props

2020-09-02 16:58 UTC, andreyvEze commented on src/locales/en_US.js
> +  fio_domain_reg_text: 'Need to note that you need to use FIO to register an address on a custom domain.',
Note that you need to use FIO...

2020-09-08 18:23 UTC, andreyvEze commented
approved

2020-09-10 17:37 UTC, paullinator requested changes

2020-09-10 17:37 UTC, paullinator commented on src/components/scenes/FioDomainRegisterScene.js
> +class FioDomainRegister extends React.Component<Props, LocalState> {
Please use React.PureComponent

2020-09-10 17:37 UTC, paullinator commented on src/components/scenes/FioDomainRegisterSelectWalletScene.js
> +              Alert.alert(
Do not use the system alert. Use an airship modal instead. ButtonModal is ideal and easy to use.

2020-09-10 17:37 UTC, paullinator commented on src/components/scenes/FioNameConfirmScene.js
> +                Alert.alert(s.strings.fio_address_register_pay_title, s.strings.fio_address_register_pay, [{ text: s.strings.string_ok_cap }])
Do not use the system alert. Use an airship modal instead. ButtonModal is ideal and easy to use.

2020-09-10 17:37 UTC, paullinator commented on src/components/scenes/FioNameConfirmScene.js
> +          Alert.alert(
Do not use the system alert. Use an airship modal instead. ButtonModal is ideal and easy to use.

2020-09-10 17:37 UTC, paullinator commented on src/components/scenes/FioDomainRegisterSelectWalletScene.js
> +class FioDomainRegisterSelectWallet extends React.Component<Props, LocalState> {
Please use React.PureComponent

2020-09-10 17:37 UTC, paullinator commented on src/components/scenes/FioNameConfirmScene.js
> +class FioNameConfirm extends React.Component<Props, LocalState> {
Please use React.PureComponent

2020-09-11 16:54 UTC, paullinator approved these changes

2020-09-11 16:55 UTC, paullinator commented
Approved but cannot merge until the latest account-based repo is published and upgraded

2020-09-18 00:14 UTC, merged