New themed modal for option selections
EdgeApp/edge-react-gui pull request #2180
Opened 2020-09-24 07:37 UTC by amanalili

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2020-09-24 23:36 UTC, amanalili commented on src/components/common/WalletListMenu.js
>  // @flow
Implement all logic to the WalletListModalMenu itself

2020-09-30 23:58 UTC, amanalili commented on src/components/common/WalletListRow.js
> +                  <Text style={styles.rowOptionsIcon}>&#8942;</Text>
make a const on the top for the option dot

2020-09-30 23:58 UTC, amanalili commented on src/components/common/WalletListRow.js
>  const rowCurrencyOverlaySize = scale(23.3)
@paullinator should rowCurrencyOverlaySize be inside the stylesheet?

2020-09-30 23:58 UTC, amanalili commented on src/components/modals/WalletListMenuModal.js
> +import { WALLET_LIST_MENU } from '../../constants/WalletAndCurrencyConstants.js'
Put option unicode constant here

2020-09-30 23:59 UTC, thehobbit85 requested changes
Fix Art's comments

2020-10-01 00:59 UTC, thehobbit85 approved these changes

2020-10-01 00:59 UTC, merged