Upgrade to @bugsnag/react-native v7.3.5
EdgeApp/edge-react-gui pull request #2189
Opened 2020-10-01 22:41 UTC by swansontec

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [x] Tested on iOS Tablet
- [x] Tested on small Android
- [ ] n/a

2020-10-01 22:48 UTC, swansontec commented
![simulator_screenshot_65D1628F-A662-4047-A169-88BD87B09B5C](https://user-images.githubusercontent.com/276214/94870865-83561c80-03fd-11eb-88c9-8556197eea5c.png)

2020-10-01 23:42 UTC, paullinator requested changes

2020-10-01 23:42 UTC, paullinator commented on src/locales/en_US.js
> +    'We are sorry, but something has gone wrong. Please report this crash to support@edge.app, and we will try to fix the bug.\n\nFeel free to kill and restart the app.',
Please change text to 

"We're sorry but something went wrong. Please kill and restart the app to continue using Edge.\n\nIf the problem persists, contact us at support@edge.app, and we'll do our best to fix the problem."

2020-10-01 23:42 UTC, paullinator commented on src/locales/en_US.js
> +  error_boundary_title: 'Oops',
Change to "Oops!"

2020-10-12 23:01 UTC, thehobbit85 approved these changes

2020-10-13 00:12 UTC, merged