ui2: Sliding of Wallet List Row to go to Send/Receive screen
EdgeApp/edge-react-gui pull request #2253
Opened 2020-11-24 11:41 UTC by amanalili

- Upgrade react-native-swipe-list-view
- Refactor code to have the SwipeRow stack inside the WalletListRow or
  WalletListEmptyRow
- Remove keyExtractor and provide key when getting wallet list
- Change options icon from vertical to horizontal
- Wallet List Row tapping of icon to go to send/receive screen
- Wallet List Row to go to send/receive screen when slid to 75% of the width

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2020-11-26 01:01 UTC, paullinator approved these changes

2020-11-26 01:24 UTC, amanalili commented on src/components/themed/WalletListRow.js
> +  handleSwipeValueChange = ({ value }) => {
Use rowOpen and rowClose to trigger change in hidden view

2020-11-26 01:24 UTC, amanalili commented on src/components/themed/WalletListRow.js
> +  openScene(key: string) {
Add class variable to prevent multiple calls

2020-11-26 01:41 UTC, paullinator requested changes
see comments

2020-12-01 01:18 UTC, paullinator approved these changes

2020-12-01 10:14 UTC, closed without merging