ui2: Themed Header component
EdgeApp/edge-react-gui pull request #2262
Opened 2020-11-27 02:05 UTC by amanalili

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2020-11-27 04:49 UTC, paullinator requested changes

2020-11-27 04:49 UTC, paullinator commented on src/components/navigation/HeaderWalletSelector.js
> +    selectedWalletName: UI_SELECTORS.getSelectedWallet(state) ? UI_SELECTORS.getSelectedWallet(state).name : null,
don’t use simple selectors. they are being deprecated

2020-11-27 04:49 UTC, paullinator commented on src/components/navigation/HeaderWalletSelector.js
> +    selectedWalletName: UI_SELECTORS.getSelectedWallet(state) ? UI_SELECTORS.getSelectedWallet(state).name : null,
just access the state directly

2020-11-27 04:49 UTC, paullinator commented on src/components/navigation/HeaderWalletSelector.js
> +    selectedWalletName: UI_SELECTORS.getSelectedWallet(state) ? UI_SELECTORS.getSelectedWallet(state).name : null,
like the old code did

2020-11-27 04:49 UTC, paullinator commented on src/components/navigation/HeaderWalletSelector.js
> +  isNameOnly?: boolean
change to showNameOnly

2020-11-27 04:49 UTC, paullinator commented on src/components/Main.ui.js
> -                renderRightButton={this.renderEmptyButton()}
wrong commit title. you are removing the empty button not back button

2020-11-27 16:11 UTC, amanalili commented on src/components/navigation/HeaderWalletSelector.js
> +  isNameOnly?: boolean
changed to showWalletNameOnly

2020-11-27 16:12 UTC, amanalili commented
Fixed comments

2020-11-28 00:18 UTC, paullinator approved these changes

2020-11-30 01:30 UTC, closed without merging