Send confirmation
EdgeApp/edge-react-gui pull request #2331
Opened 2021-01-05 23:14 UTC by wolverineks

no visual changes

not sure what this code does or how to test that it didn't break anything, but this code looks to me like it doesnt change anything

tested on android emulator
- [X] spend max updates
- [X] change fee updates
- [X] flip input still flips
- [X] crypto amount updates
- [X] fiat amount updates

2021-02-02 23:53 UTC, swansontec requested changes
I think I found a bug? Let me know if you agree. In any case, I would like to rebase onto the latest develop before merging.

2021-02-02 23:53 UTC, swansontec commented on src/components/scenes/SendConfirmationScene.js
> +    const showSpinner = !(feeCalculated || errorMsg || nativeAmount === '0' || !this.state.showSpinner || !this.props.pending)
If we invert this, we get `const showSpinner = !feeCalculated && !errorMsg && nativeAmount !== '0' && this.state.showSpinner && this.props.pending`, but before it was `... this.state.showSpinner || this.props.pending`, so we have an `&&` turned to a `||`, which is a change in logic.

2021-02-05 02:12 UTC, wolverineks commented
so, i took another stab at this and it's changed behavior somehow
to me, it looks like it should work, but it doesnt

typing in '$1' gets rewritten as '$0.99'
is that a bug anyone has seen before?

2021-02-05 03:53 UTC, wolverineks commented
ok, so `SecondaryDisplayDenomination` and the spinner state were moved into render, and the forceGuiCounter stuff was moved into `componentDidMount`

the forceGuiCounter stuff looks like it should work directly in render, but apparently it doesnt

this version looks like it works

2021-02-05 18:39 UTC, swansontec approved these changes
This version looks much better, thanks.

2021-02-05 18:39 UTC, merged

2021-02-05 19:06 UTC, swansontec commented
@wolverineks I merged this, but:

1. The PR was never rebased onto to the latest develop.
2. Hence, the unit tests broke after the merge.

I have fixed the unit tests directly on develop, but I should have insisted on a rebase before merging this. Oops.

2021-02-05 19:31 UTC, wolverineks commented
> @wolverineks I merged this, but:
> 
> 1. The PR was never rebased onto to the latest develop.
> 2. Hence, the unit tests broke after the merge.
> 
> I have fixed the unit tests directly on develop, but I should have insisted on a rebase before merging this. Oops.

whoops, sorry 'bout that