Show progressbar on resync
EdgeApp/edge-react-gui pull request #2411
Opened 2021-01-29 20:58 UTC by andreyvEze

2021-02-01 06:06 UTC, paullinator requested changes

2021-02-01 06:06 UTC, paullinator commented on src/components/themed/WalletProgressIcon.js
> +      }, 5000)
Five seconds seems like overkill. Please set to 500 ms here as well as on line 37

2021-02-01 06:06 UTC, paullinator commented on src/reducers/scenes/WalletsReducer.js
> +        [action.data.walletId]: 0
Progress at zero does not show any progress indicator. Set to 5 instead

2021-02-01 13:16 UTC, andreyvEze commented
@paullinator just as summary of these changes, e top progress-bar also would animate backwards, is it ok?

2021-02-01 17:19 UTC, paullinator commented
> @paullinator just as summary of these changes, top progress-bar also would animate backwards, is it ok?

Sure. And that is fine

2021-02-03 17:47 UTC, thehobbit85 approved these changes

2021-02-03 17:47 UTC, merged