Fix bug on wallet list modal where if wallet is created then tries to select it after but created wallet is not yet on the redux state.
EdgeApp/edge-react-gui pull request #2447
Opened 2021-02-22 07:21 UTC by amanalili

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2021-02-23 02:28 UTC, paullinator requested changes

2021-02-23 02:28 UTC, paullinator commented on src/components/modals/WalletListModal.js
> +      const checkWalletsThenSelect = async () => {
No need to make this an async function.

2021-02-23 02:28 UTC, paullinator commented on src/components/modals/WalletListModal.js
> +          await setTimeout(() => {}, 50)
No need to await. Just set `checkWalletsThenSelect` as the callback of setTimeout.

2021-02-24 06:42 UTC, amanalili commented
Fixed

2021-02-24 06:53 UTC, paullinator requested changes

2021-02-24 06:53 UTC, paullinator commented on src/components/modals/WalletListModal.js
> +          setTimeout(() => checkWalletsThenSelect(), 50)
Why do you have the anonymous function? just put checkWalletsThenSelect as the callback

2021-02-25 05:00 UTC, paullinator approved these changes

2021-02-25 05:00 UTC, merged