Fix crash upon login going to walllet list scene. Have default values when getting crypto amount on wallet list row
EdgeApp/edge-react-gui pull request #2476
Opened 2021-03-09 08:57 UTC by amanalili

… #### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2021-03-18 20:22 UTC, amanalili commented on src/components/themed/WalletList.js
> +    const balance = !isNaN(balanceString) ? balanceString : '0'
fixed

2021-03-19 00:08 UTC, amanalili commented on src/components/themed/WalletList.js
> +    const preliminaryCryptoAmount = truncateDecimals(bns.div(balance, denominationMultiplier, DIVIDE_PRECISION), maxConversionDecimals)
throw an Error when "Cannot operate on base16 float values" with GuiWallet currency code, balance value, denomination multiplier

2021-03-22 21:54 UTC, paullinator requested changes

2021-03-22 21:54 UTC, paullinator commented on src/components/themed/WalletList.js
> +      console.log(error)
Still need to throw here. Otherwise you are hiding some other possible error

2021-03-23 01:44 UTC, paullinator approved these changes

2021-03-23 01:44 UTC, merged