Help modal ui2 design.
EdgeApp/edge-react-gui pull request #2540
Opened 2021-04-15 17:08 UTC by andreyvEze

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2021-04-17 08:41 UTC, thehobbit85 requested changes
Address Comment

2021-04-17 08:41 UTC, thehobbit85 commented on src/components/themed/SelectableRow.js
> +          <IonIcon size={theme.rem(1.5)} color={arrowColor || theme.icon} name="chevron-forward-outline" style={styles.iconStyle} />
Don't just pass in the 'arrowColor' as prop.
Instead, pass in a prop called 'tappable' and then ```color={tappable ? theme.iconTappable :  theme.icon}```

As a general rule, don't pass styles as props.

2021-04-20 12:45 UTC, andreyvEze commented
> Address Comment.
> And also the icons look way off from the design.
> <img alt="Screen Shot 2021-04-17 at 01 42 30" width="261" src="https://user-images.githubusercontent.com/4012041/115107238-7d99d180-9f1e-11eb-99cc-b0e116c0b534.png">

I found similar from out icon lib. should I use exact same from design?

2021-04-21 21:42 UTC, thehobbit85 approved these changes

2021-04-22 09:16 UTC, merged