Visual issue on the italian UI - "+ Add token" overlaps "+ add Wallet"
EdgeApp/edge-react-gui pull request #2614
Opened 2021-05-17 09:57 UTC by dbo1dyrev

<img width="399" alt="Screenshot 2021-05-17 at 12 44 38" src="https://user-images.githubusercontent.com/68349436/118470423-57c73e80-b70f-11eb-9b10-264a379ce9a5.png">
<img width="398" alt="Screenshot 2021-05-17 at 12 44 13" src="https://user-images.githubusercontent.com/68349436/118470439-5b5ac580-b70f-11eb-9dad-2acd5b2a6264.png">

2021-05-18 02:19 UTC, thehobbit85 approved these changes

2021-05-18 02:23 UTC, thehobbit85 requested changes
The '+ Add Wallet' and '+ Add Token' buttons should both have the same padding from the left and the right (centered), and not aligned to the left.

Like in this picture:

![image](https://user-images.githubusercontent.com/4012041/118580874-819b5800-b745-11eb-9460-492cc40ed69a.png)

2021-05-19 08:22 UTC, dbo1dyrev commented
<img width="400" alt="Screenshot 2021-05-19 at 11 18 41" src="https://user-images.githubusercontent.com/68349436/118780127-6854f180-b894-11eb-8872-301c0b4667d5.png">
<img width="408" alt="Screenshot 2021-05-19 at 11 18 05" src="https://user-images.githubusercontent.com/68349436/118780137-6ab74b80-b894-11eb-9429-f9da022a44a7.png">

2021-05-20 23:39 UTC, thehobbit85 approved these changes

2021-05-20 23:39 UTC, merged