Use reanimated for the Fade component
EdgeApp/edge-react-gui pull request #2625
Opened 2021-05-18 17:49 UTC by dbo1dyrev

https://user-images.githubusercontent.com/68349436/118699591-60f10200-b81a-11eb-910e-c5a14374f567.mov

2021-05-21 06:00 UTC, thehobbit85 requested changes
See comments

2021-05-22 05:31 UTC, thehobbit85 commented on src/components/themed/Fade.js
> +// $FlowFixMe
The whole point of having the "future-commit" was to remove this `$FlowFixMe` ;)

2021-05-22 05:33 UTC, thehobbit85 requested changes
Forgot to remove the `$FlowFixMe` ;)

2021-05-24 10:59 UTC, dbo1dyrev commented
Start using `util/hooks`

2021-05-24 16:51 UTC, thehobbit85 approved these changes

2021-05-24 16:51 UTC, merged