New OutlinedField component
EdgeApp/edge-react-gui pull request #2673
Opened 2021-06-04 17:52 UTC by andreyvEze

https://user-images.githubusercontent.com/22767467/120843440-c4976100-c576-11eb-8bda-21ff8dd68eb9.mov

2021-06-08 19:25 UTC, thehobbit85 requested changes
see comments

2021-06-08 19:25 UTC, thehobbit85 commented on src/components/themed/EdgeOutlinedField.js
> +  })
Avoid this code duplication.
Instead, create a function like this as a const:
```
const cornerStyle = (borders: string[]) => () => {
    const color = placeholderSize.value > 0 ? interpolateColor(colorMap.value, [0, 1, 2], [inactiveColor, activeColor, errorColor]) : inactiveColor
    return borders.reduce((res, border) => ({ ...res, [border]: color}), {})
  }
```

And then you can use it to create the animatedStyles like this:


```
const animatedLeftCornerStyle = useAnimatedStyle(cornerStyle(['borderTopColor', 'borderLeftColor']))
```

2021-06-08 22:57 UTC, thehobbit85 commented
There is one more place that you need to replace the text component: 
https://github.com/EdgeApp/edge-react-gui/blob/37937adfc79a21fd07f2981b136aad2ede5a288e/src/components/themed/ManageTokensHeader.js#L44

It's the new manage token scene.

2021-06-11 02:37 UTC, thehobbit85 requested changes
See comment

2021-06-11 16:26 UTC, andreyvEze commented on src/components/themed/EdgeOutlinedField.js
> +        : inactiveColor
ok, sure

2021-06-12 01:56 UTC, thehobbit85 approved these changes

2021-06-12 01:57 UTC, merged