Refactoring wallet list menu modal
EdgeApp/edge-react-gui pull request #2704
Opened 2021-06-22 11:21 UTC by axenov-it

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2021-06-22 11:28 UTC, axenov-it commented
This functionality have: 

1) Refactoring code with react hooks 
2) Added types for useDispatch and useSelector from react-redux lib 
3) Implemented splittable option for wallet list modal menu with account.listSplittableWalletTypes of handler

![1](https://user-images.githubusercontent.com/67971974/122916860-06414d80-d366-11eb-8223-afd73224cbee.png)
![2](https://user-images.githubusercontent.com/67971974/122916873-0a6d6b00-d366-11eb-9f95-95f0abbbfe74.png)

2021-07-01 08:30 UTC, thehobbit85 requested changes
See comments

2021-07-01 08:30 UTC, thehobbit85 commented on src/components/modals/WalletListMenuModal.js
> +    if (isArray(currencyCodes) && !currencyCodes.includes(currencyCode)) continue
Remove `lodash`. Just use `Array.isArray()`

2021-07-01 08:30 UTC, thehobbit85 commented on src/components/modals/WalletListMenuModal.js
> +  if (splittable.length) {
This is not a boolean, so you should use exact comparison, something like: 
`splittable.length !== null && splittable.length > 0`

2021-07-02 10:23 UTC, thehobbit85 approved these changes

2021-07-02 10:24 UTC, merged