William/connector cleanup
EdgeApp/edge-react-gui pull request #2740
Opened 2021-07-09 22:42 UTC by swansontec

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2021-07-15 18:57 UTC, thehobbit85 commented
/rebase-autosquash

2021-07-20 16:48 UTC, thehobbit85 requested changes

2021-07-20 17:13 UTC, swansontec commented on src/components/scenes/CreateWalletAccountSelectScene.js
> +    async createAccountBasedWallet(walletName: string, walletType: string, fiatCurrencyCode: string, popScene: boolean, selectWallet: boolean) {
Nobody even awaits this, so it's no good.

2021-07-20 17:15 UTC, swansontec commented on src/components/scenes/FioAddressRegisterScene.js
> +      return dispatch(createFioWallet())
Could add async/await for clarity.

2021-07-20 17:16 UTC, swansontec commented on src/components/scenes/FioDomainRegisterScene.js
> +    createFioWallet() {
Could add async/await for clarity.

2021-07-20 17:16 UTC, swansontec commented on src/components/scenes/RequestScene.js
> +      return dispatch(refreshAllFioAddresses())
Just await the result, no return.

2021-07-20 17:17 UTC, swansontec commented on src/components/scenes/TransactionsExportScene.js
> +  null
Change all these to `(dispatch: DispatchProps) => ({})`

2021-07-20 17:33 UTC, swansontec commented on src/components/themed/SelectFioAddress.js
> +    }
Derp, could combine these into one.

2021-07-20 17:33 UTC, swansontec commented on src/components/themed/WalletList.js
> +    const { isModal, onPress, selectWallet, showSlidingTutorial, wallets } = this.props
Something about creating tokens with a different wallet selected than the one you want, it should crash / fail in some way.

2021-07-20 17:33 UTC, swansontec commented on src/components/scenes/RequestScene.js
> +      return dispatch(refreshAllFioAddresses())
Nope, it's never awaited, so we can make it return `void` instead.

2021-07-21 02:18 UTC, thehobbit85 approved these changes

2021-07-21 02:18 UTC, thehobbit85 commented
/rebase-autosquash

2021-07-21 16:31 UTC, merged