Add custom token ui2
EdgeApp/edge-react-gui pull request #2750
Opened 2021-07-15 19:25 UTC by dbo1dyrev

Wip

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2021-07-15 20:09 UTC, dbo1dyrev commented
Additional info: without autocomplete api you can't see this modal

2021-07-22 08:30 UTC, thehobbit85 requested changes
PR 1:
Add new string constants related to Add Token scene
Add "defaultBorderColor" property to app theme
Add "fontFaceMedium" property to app theme and replace in all places … 
Add additional functions to the utils allowing to get ready edge-styles
Add the abilities to resize edges and display text as a warning in th…
Remove:
1.Add the ability for the SecondaryButton to display bold text
PR 2:
Add the ability for the SceneHeader to display bold text 
Add the ability for the ModalTitle to display bold text
Instead of those 2 PR’s, everything should just be default bold, and if any scene would require none default, we would fix it later in a !fixup commit.
PR 3:
Update Fade component: use pointerEvents instead of removing children…  
Add fade animation hook
Update Fade component to use fade animation hook
PR 4:
Add Checkbox component to the repo - Fix types based on this on in the login-ui:
https://github.com/EdgeApp/edge-login-ui/blob/e7fd8dc80d1ad66a0f5ab9a89f64450191444e13/packages/edge-login-ui-rn/src/components/themed/Checkbox.js
PR 5:
Add MismatchTokenParamsModal component to the repo - Remove “bolds”
PR 6:
Redesign AddToken scene
Remove AddToken title from main router render

2021-07-22 08:30 UTC, thehobbit85 commented on src/components/scenes/AddTokenScene.js
> +
Move to utility function

2021-07-22 08:30 UTC, thehobbit85 commented on src/components/scenes/AddTokenScene.js
> +export const AddToken = ({ addTokenPending, currentCustomTokens = [], currencyInfos, wallet, walletId, currencyWallet, addNewToken, onAddToken }: Props) => {
Should be scrollable

2021-07-22 08:30 UTC, thehobbit85 commented on src/components/scenes/AddTokenScene.js
> +        <EdgeTextFieldOutlined
Should also have validation - Should "clean" and not allow non number chars.

2021-07-22 08:30 UTC, thehobbit85 commented on src/components/themed/Checkbox.js
> +    <TouchableWithoutFeedback onPress={() => onChange(!value)} disabled={disabled}>
Should only be able to tap on checkbox and not the entire row

2021-07-22 08:30 UTC, thehobbit85 commented on src/components/scenes/AddTokenScene.js
> +    }
Separate logic

2021-07-22 08:30 UTC, thehobbit85 commented on src/components/scenes/AddTokenScene.js
> +    currencyInfos: [] // TODO: replace it with real data when it will be available
Select better name

2021-07-23 06:05 UTC, closed without merging