Change ETH import description
EdgeApp/edge-react-gui pull request #2751
Opened 2021-07-16 14:45 UTC by axenov-it

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2021-07-16 14:49 UTC, axenov-it commented
This functionality added locales for import wallet input and title:

ETH supports both seeds and private key
ETC supports both seeds and private key
DAI → token, so not possible to import it (you need to import ETH)
XTZ supports both seeds and private key
BNB supports both seeds and private key
RBTC supports both seeds and private key
XLM supports only private key
XRP supports only private key

![image](https://user-images.githubusercontent.com/67971974/125966048-9da808cd-52c3-4ae8-bada-88548a9a427e.png)
![image](https://user-images.githubusercontent.com/67971974/125966172-b9ac434c-5a01-439a-9263-ed5ca757e956.png)

2021-07-23 06:44 UTC, thehobbit85 requested changes
Fix

2021-07-23 06:44 UTC, thehobbit85 commented on src/locales/en_US.js
> +  create_wallet_import_key_instructions: 'Enter your private key to verify and restore the associated wallet:',
Why is there a ':' at the end of the line?
It wasn't in the task on Asana. Remove it.

2021-07-23 15:32 UTC, thehobbit85 approved these changes

2021-07-23 15:32 UTC, merged