William/no modal manager
EdgeApp/edge-react-gui pull request #2816
Opened 2021-08-05 22:31 UTC by swansontec

### Changed

- Add a submit button to the following modals:
  - Fio address registration entry
  - Fio domain registration entry
  - Paste private key (scan scene)
  - Upload logs notes
- Upgrade the following modals to use modern theming:
  - `RawTextModal` (Exchange details & raw keys)
  - Wallet name entry
  - Custom plugin URI
  - Promotion code entry
  - Password validation (view wallet keys, unlock settings)
  - Import wallet error
  - Edge login error
- Replace the `InfoModal` component with a `ButtonsModal`.

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [x] Tested on iOS Tablet
- [x] Tested on small Android
- [ ] n/a

2021-08-05 22:33 UTC, swansontec commented
![Screenshot_20210805-151054_Edge](https://user-images.githubusercontent.com/276214/128429822-83d5d84b-bca9-447e-8472-54d254a04147.png)
![Screenshot_20210805-151241_Edge](https://user-images.githubusercontent.com/276214/128429831-c7b43410-cfce-4a46-9eff-45a93317895a.png)

2021-08-05 22:36 UTC, swansontec commented
Text modals look like this:

![Screenshot_20210803-151124_Edge](https://user-images.githubusercontent.com/276214/128430063-870f3cd4-bd5d-4780-abc7-7c405b6fed25.png)

2021-08-09 17:23 UTC, swansontec commented
Built on top of #2819

2021-08-09 23:58 UTC, thehobbit85 commented
/rebase-autosquash

2021-08-10 19:43 UTC, thehobbit85 requested changes

2021-08-10 19:43 UTC, thehobbit85 commented on src/components/modals/TextInputModal.js
> +        }
Flip around

2021-08-10 21:14 UTC, swansontec commented on src/components/modals/TextInputModal.js
> +        }
Yeah, much nicer that way!

2021-08-10 21:14 UTC, merged