William/outlined text field
EdgeApp/edge-react-gui pull request #2852
Opened 2021-08-16 23:17 UTC by swansontec

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [x] Tested on iOS Tablet
- [x] Tested on small Android
- [ ] n/a

2021-08-16 23:35 UTC, swansontec commented
![simulator_screenshot_DE49FFF9-8E61-4517-8289-AE81C916887E](https://user-images.githubusercontent.com/276214/129641890-7005d9cf-fe8e-404f-a2eb-582248a001f7.png)
![simulator_screenshot_AFD59064-550C-4C4A-B635-4B791B0D39B1](https://user-images.githubusercontent.com/276214/129641903-ece5ebbc-42e9-4c3f-94d9-338dfde190d8.png)

2021-08-18 21:30 UTC, peachbits requested changes

2021-08-18 21:30 UTC, peachbits commented on src/components/themed/OutlinedTextInput.js
> +        <Animated.Text style={[styles.errorText, errorStyle]}>{error}</Animated.Text>
ellipaize

2021-08-18 21:45 UTC, swansontec commented on src/components/themed/OutlinedTextInput.js
> +        <Animated.Text style={[styles.errorText, errorStyle]}>{error}</Animated.Text>
Fixed.

2021-08-18 22:00 UTC, merged