Rethemed KYC modal to match new dark theme
EdgeApp/edge-react-gui pull request #2868
Opened 2021-08-24 17:59 UTC by itayplav

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [x] Tested on small Android
- [ ] n/a
![image](https://user-images.githubusercontent.com/4023066/130666410-303c9f1f-cbfa-4191-a2ac-0f5b4ab65970.png)

2021-08-25 08:32 UTC, thehobbit85 requested changes

2021-08-28 14:07 UTC, swansontec commented
@itayplav, please rebase this onto develop & fix the conflicts. Then pass the task back to @thehobbit85 for review.

2021-09-01 02:02 UTC, thehobbit85 requested changes

2021-09-01 17:46 UTC, itayplav commented on src/components/modals/SwapVerifyTermsModal.js
> +    fontSize: theme.rem(0.84),
It references the `small` font size in [textStyles.js](https://github.com/EdgeApp/edge-react-gui/blob/13b995842ad952740304372d174a733d65c03640/src/styles/common/textStyles.js#L44-L44)

2021-09-01 17:54 UTC, itayplav commented on src/components/modals/SwapVerifyTermsModal.js
> +          <Text style={styles.linkText} onPress={() => Linking.openURL(termsUri)}>
@swansontec discourages the use of EdgeText

2021-09-02 18:17 UTC, swansontec requested changes
Three tiny changes.

2021-09-02 18:17 UTC, swansontec commented on src/actions/CryptoExchangeActions.js
> -
Please put back the blank line after imports.

2021-09-02 18:17 UTC, swansontec commented on src/actions/CryptoExchangeActions.js
> +    // const
Remove this extra const.

2021-09-02 18:17 UTC, swansontec commented on src/components/scenes/CryptoExchangeQuoteScene.js
> +    fromDenomination: state.cryptoExchange.fromWalletPrimaryInfo.displayDenomination.name ?? '',
The `displayDenomination.name` isn't optional, so no need for `?? ''`

2021-09-02 18:18 UTC, swansontec commented on src/components/scenes/CryptoExchangeQuoteScene.js
> +    fromDenomination: state.cryptoExchange.fromWalletPrimaryInfo.displayDenomination.name ?? '',
The other `?? ''` are still needed, though. It's just this one line.

2021-09-03 18:14 UTC, swansontec approved these changes
I made the 3 tiny changes myself. Approved.

2021-09-03 18:22 UTC, merged