Send Scene Flip Input Amount Modal Redesign
EdgeApp/edge-react-gui pull request #2988
Opened 2021-11-11 10:38 UTC by amanalili

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [x] Tested on small Android

2021-12-14 01:10 UTC, Jon-edge commented
General comment: Fix the spacing on android. Large gap between keyboard and modal contents. Use invisible components to pad for android only?

2021-12-14 18:31 UTC, Jon-edge requested changes

2022-01-11 00:48 UTC, Jon-edge commented on src/components/modals/FlipInputModal2.js
> +          <View>
TouchableWithoutFeedback only accepts one child

2022-01-11 09:50 UTC, thehobbit85 approved these changes

2022-01-11 09:56 UTC, merged