Move zcash checkpoints from edge-currency-accountbased into android asset folder
EdgeApp/edge-react-gui pull request #2995
Opened 2021-11-15 22:45 UTC by peachbits

2021-11-15 22:46 UTC, peachbits commented
Relies on https://github.com/EdgeApp/edge-currency-accountbased/pull/339

2021-11-16 08:37 UTC, thehobbit85 requested changes

2021-11-16 08:37 UTC, thehobbit85 commented on scripts/prepare.sh
> +cp -R node_modules/edge-currency-accountbased/lib/zcash/zecCheckpoints android/app/build/intermediates/merged_assets/debug/out/saplingtree/mainnet
Make it a bit more robust by adding `2>/dev/null || :` to the end of this line so that it would not fail if the zcash checkpoint folder is not there.

2021-11-16 21:01 UTC, peachbits commented
/rebase

2021-11-16 21:02 UTC, peachbits commented
/rebase

2021-11-16 21:03 UTC, merged