Select Crypto wallet when adding token
EdgeApp/edge-react-gui pull request #3002
Opened 2021-11-18 16:23 UTC by amanalili

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2021-11-25 22:47 UTC, thehobbit85 commented on src/constants/WalletAndCurrencyConstants.js
> +export const getCurrenciesSelectedInfo = (info: 'isPrivateKeySweepable' | 'isCustomTokensSupported'): string[] => {
You don't need this function, just use filter directly instead (replace the 'info' with whatever you need in the scene):
```js
Object.keys(SPECIAL_CURRENCY_INFO).filter(currencyCode => SPECIAL_CURRENCY_INFO[currencyCode]['info'] != null)
```

2021-11-25 23:53 UTC, thehobbit85 requested changes
See comment

2021-11-30 13:45 UTC, thehobbit85 commented
https://user-images.githubusercontent.com/4012041/144058396-952b2844-2a72-4723-9b16-a47b1c32ed7a.mov

2021-11-30 23:46 UTC, Jon-edge approved these changes

2021-12-01 01:37 UTC, merged