Jon/side menu themed future qr
EdgeApp/edge-react-gui pull request #3013
Opened 2021-11-26 02:26 UTC by Jon-edge

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ x] Tested on iOS Tablet
- [ x] Tested on small Android

https://user-images.githubusercontent.com/90650827/143517488-34095715-363d-46f6-989c-e7a4426e1f12.mp4
![Simulator Screen Shot - iPhone 13 - 2021-11-25 at 18 02 20](https://user-images.githubusercontent.com/90650827/143517524-7cc14680-c7b8-4152-a4f7-0d3b5d8ebc24.png)
![Simulator Screen Shot - iPhone 13 - 2021-11-25 at 18 02 16](https://user-images.githubusercontent.com/90650827/143517528-1dc6c0de-ae45-4345-bdbf-98484ec3a3a1.png)

2021-11-28 18:28 UTC, lionmuphasa approved these changes

2021-11-28 18:28 UTC, lionmuphasa commented on src/assets/vector/config.json
> +      "uid": "078bf075ad50e41c3847a9908c813347",
12yLRFTJtEqSDjDduBRM1VGps2JueD5J1W

2021-11-30 03:05 UTC, thehobbit85 requested changes

2021-11-30 03:05 UTC, thehobbit85 commented on src/components/themed/ControlPanel.js
> +                <View style={styles.rowIconContainer} />
remove

2021-11-30 03:05 UTC, thehobbit85 commented on src/components/themed/ControlPanel.js
> +    borderBottomLeftRadius: theme.rem(2),
borderBottomRightRadius: theme.rem(2),

2021-11-30 21:26 UTC, lionmuphasa approved these changes

2021-12-01 00:14 UTC, closed without merging