Add USDT to simplex
EdgeApp/edge-react-gui pull request #3016
Opened 2021-11-30 13:47 UTC by thehobbit85

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2021-11-30 21:59 UTC, peachbits requested changes

2021-11-30 21:59 UTC, peachbits commented on src/constants/plugins/sellPluginList.json
> +      "USDT"
Should not be in sell

2021-11-30 21:59 UTC, peachbits commented on src/constants/plugins/sellPluginList.json
> +      "USDT"
Remove the whole thing

2021-12-01 03:37 UTC, thehobbit85 commented
Approved OTS by @peachbits

2021-12-01 03:49 UTC, merged