Implement Token Terms And Agreement Modal when adding token for the first time
EdgeApp/edge-react-gui pull request #3042
Opened 2021-12-12 13:13 UTC by amanalili

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android

2021-12-14 18:35 UTC, Jon-edge requested changes

2021-12-17 21:12 UTC, Jon-edge requested changes

2021-12-17 21:12 UTC, Jon-edge commented on src/util/tutorial.js
> +export const setUserTutorialList = async (data: UserTutorialList, disklet: Disklet): Promise<void> => await disklet.setText(TUTORIAL, JSON.stringify(data))
The new hasAgreedToTokenTerms is not related to the tutorial.

1. Split saving of both vars into separate files
2. Don't save a single piece of data as a json, simply save the var without an object wrapper.
```js
disklet.setText('hasAgreedToTokensTerms', 'false')
```

2021-12-21 01:00 UTC, Jon-edge commented on src/components/scenes/ManageTokensScene.js
> +    if (this.state.enabledList.length > 0 && !(await checkTokenTermsAndAgreement(wallets, disklet))) return
Edit on last comment: checkTokenTermsAndAgreement returns a boolean. If we are not checking this for safety then these lines can all be removed.

2021-12-21 01:50 UTC, Jon-edge commented on src/components/modals/ConfirmContinueModal.js
> +            {isAgreed && <Ionicons name={CHECKED_ICON} color={theme.iconTappable} size={theme.rem(0.75)} />}
Cannot find the FontAwesome 'ok' that we were looking at the other day. Updated to use the same Feather icon lib as the ControlPanel, the checkmark looks close to Figma.

2021-12-22 08:01 UTC, peachbits approved these changes

2021-12-22 08:01 UTC, merged