Jon/fix/bitPayV2Eth
EdgeApp/edge-react-gui pull request #3132
Opened 2022-02-01 02:47 UTC by Jon-edge

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ x] Tested on iOS Tablet
- [ x] Tested on small Android
- [ ] n/a

2022-02-01 23:03 UTC, swansontec requested changes
I am working on another PR to add error translation infrastructure. Once that's done, we can rebase this.

2022-02-01 23:34 UTC, thehobbit85 commented
> I am working on another PR to add error translation infrastructure. Once that's done, we can rebase this.

I agree that that would be better. The question is, would it be ready to be merged today? Since today is our deadline to finish this task.

2022-02-02 05:59 UTC, swansontec commented
PR #3139 is ready to go, and includes the new approach to error handling that we need.

2022-02-02 21:30 UTC, Jon-edge commented
> PR #3139 is ready to go, and includes the new approach to error handling that we need.

Per @thehobbit85, Reverting error-related refactors for this fix to avoid re-sweep in testing. Will pull in error handling changes #3139 and #3117 (stack trace logging) in 2.11

2022-02-02 21:35 UTC, swansontec approved these changes
OK, this needs to be rebased & squashed, but the changes look good.

2022-02-02 21:52 UTC, Jon-edge commented
/rebase

2022-02-02 21:53 UTC, Jon-edge commented
/rebase-autosquash

2022-02-03 00:50 UTC, Jon-edge commented on src/actions/BitPayActions.js
>        const { walletId, currencyCode } = walletListResult
This destructuring was not setting currencyCode with that from the walletListResult

2022-02-03 05:25 UTC, swansontec approved these changes
This final rebased version is approved.

2022-02-03 05:28 UTC, swansontec requested changes

2022-02-03 05:28 UTC, swansontec commented on src/actions/BitPayActions.js
> +    if (matchingWallets === 0) {
Actually, `.length === 0` would be needed here.

2022-02-03 05:28 UTC, swansontec commented on src/actions/BitPayActions.js
> +    const matchingWallets = Object.keys(currencyWallets).filter(key => paymentCurrencies.includes(currencyWallets[key].currencyInfo.currencyCode))
Add a type annotation, `const matchingWallets: string[]`, since Flow seems to be having trouble here.

2022-02-03 05:28 UTC, swansontec commented on src/types/BitPayError.js
> + * - CurrencyNotSupported -
Missing comment here.

2022-02-03 08:10 UTC, swansontec approved these changes
Approved with the fixup I did.

2022-02-03 11:16 UTC, merged