Feat/tomb v3 stake options
EdgeApp/edge-react-gui pull request #3292
Opened 2022-04-18 20:33 UTC by samholmes

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ ] n/a

2022-04-19 22:56 UTC, Jon-edge requested changes

2022-04-20 00:42 UTC, samholmes commented on src/plugins/stake-plugins/stakePolicy.js
>    const stakePart = policyInfo.stakeAssets.map(asset => `${asset.pluginId}:${asset.tokenId}`).join('+')
I'll sort the array deterministically.

2022-04-20 01:04 UTC, samholmes commented on src/plugins/stake-plugins/policies/cemeteryPolicy.js
> +      const tokenACurrencyCode = policyInfo.stakeAssets[0].tokenId
Discovery to do: does the order of the token address when calling addLiquidity (or similar) impact the contract call such that an incorrect amount of tokenA/B is added to the pool or if the pool is different in any way (different LP token), or not.

2022-04-20 15:47 UTC, samholmes commented on src/util/exchangeHelpers.js
> +import { EDGE_CONTENT_SERVER } from '../constants/WalletAndCurrencyConstants.js'
I suggest we create a patch/exchange-cdn branch and PR for the exchange icon CDN work. We can then make this PR and https://github.com/EdgeApp/edge-react-gui/pull/3296 dependent on it.

2022-04-20 15:58 UTC, samholmes commented on src/plugins/stake-plugins/policies/cemeteryPolicy.js
> +      const tokenACurrencyCode = policyInfo.stakeAssets[0].tokenId
Discovered: If you enter the same two token addresses into in different order, it doesn't effect the outcome of the contract call. As long as the amount parameters match the order of the given token address parameters, we're okay.

2022-04-21 00:00 UTC, Jon-edge approved these changes
gj

2022-04-21 23:04 UTC, merged