UI2 - Create wallet choice scene
EdgeApp/edge-react-gui pull request #3302
Opened 2022-04-20 22:03 UTC by peachbits

2022-04-20 22:04 UTC, peachbits commented
![Simulator Screen Shot - iPod touch (7th generation) - 2022-04-20 at 15 03 59](https://user-images.githubusercontent.com/41451710/164332643-69f7ab73-10c1-40bc-9181-8a8fc905e77c.png)

2022-04-29 19:17 UTC, paullinator requested changes

2022-04-29 19:17 UTC, paullinator commented on src/components/scenes/CreateWalletChoiceScene.js
> +  const onSelectRestore = () => {
use `useCallback`

2022-04-29 19:17 UTC, paullinator commented on src/components/scenes/CreateWalletChoiceScene.js
> +  const onSelectNew = () => {
use `useCallbackà

2022-04-29 19:17 UTC, paullinator commented on src/components/scenes/CreateWalletChoiceScene.js
> +  const svgScale = theme.rem(1 / 16)
why all the magic number?

2022-04-29 19:17 UTC, paullinator commented on src/components/scenes/CreateWalletChoiceScene.js
> +    marginTop: theme.rem(1),
Can just do `marginVertical`

2022-04-29 19:17 UTC, paullinator commented on src/components/scenes/CreateWalletChoiceScene.js
> +      <MainButton alignSelf="stretch" label={s.strings.create_wallet_choice_new_button} marginRem={[1, 1]} type="secondary" onPress={onSelectNew} />
Declare the [1, 1] as a const outside of component.

2022-05-05 05:08 UTC, thehobbit85 requested changes

2022-05-05 05:08 UTC, thehobbit85 commented on src/components/scenes/CreateWalletChoiceScene.js
> +    marginLeft: theme.rem(2.5),
marginHorizontal: theme.rem(2.5) 

;)

2022-05-06 00:27 UTC, thehobbit85 approved these changes

2022-05-06 00:28 UTC, merged