BNB and FIO fixes
EdgeApp/edge-react-gui pull request #3379
Opened 2022-05-17 08:28 UTC by peachbits

2022-05-17 17:34 UTC, swansontec requested changes
This is an amazing PR! It's wonderful to finally see all these things come together in the end.

2022-05-17 17:45 UTC, thehobbit85 commented on src/modules/FioAddress/util.js
> +    const walletName = wallet.name ?? info.initWalletName
The problem using 'sprintf(s.strings.my_crypto_wallet_name, wallet.currencyInfo.displayName)' is that it's not translatable, that's why we used the 'initWalletName' with is fully translatable (including the currency name).

So it does look like we need to revisit the 'useWalletName' hook.

2022-05-17 20:51 UTC, thehobbit85 requested changes

2022-05-17 20:51 UTC, thehobbit85 commented on src/components/themed/BuyCrypto.js
> +  tokenId?: string
Pass the 'wallet' instead of a walletID, then remove the connector in the BuyCrypto and update BuyCrypto into a functional component

2022-05-18 00:59 UTC, thehobbit85 approved these changes

2022-05-18 00:59 UTC, thehobbit85 commented
/rebase-autosquash

2022-05-18 01:11 UTC, merged