William/delete account
EdgeApp/edge-react-gui pull request #3495
Opened 2022-06-30 18:05 UTC by swansontec

This does not match the design - it is missing all the text. However, it does work.

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [x] Tested on iOS device
- [ ] Tested on Android device
- [x] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2022-07-02 00:35 UTC, samholmes approved these changes
Add comment then merge

2022-07-02 00:35 UTC, samholmes commented on src/components/themed/ThemedModal.js
> +  // TODO: The warning styles are incorrectly hard-coded:
Mention the relation to the login UI (inherited styles from there)

2022-07-06 03:33 UTC, samholmes commented on src/components/services/EdgeCoreManager.js
> +  authServer: 'https://login-test.edge.app/api'
Remove this and merge, or make it configurable from `env.json` (alternatively, `src/theme/appConfig.js`

2022-07-06 05:31 UTC, thehobbit85 requested changes
See the latest comment from sam @samholmes

2022-07-06 08:57 UTC, merged