Add create wallet/token to wallet list scene search and allow selection of parent wallet for new tokens
EdgeApp/edge-react-gui pull request #3669
Opened 2022-09-23 00:46 UTC by peachbits

2022-10-03 07:02 UTC, paullinator requested changes

2022-10-03 22:29 UTC, peachbits commented on src/components/themed/WalletList.tsx
> +    if (allowedWalletIds != null) return sortedWalletList.filter(item => item.tokenId == null && allowedWalletIds.includes(item.walletId))
sortedWalletList has both token and main chain rows so I needed to just get the rows with the main chain, however, I didn't actually use allowedWalletIds and went with a different solution for the parent wallet modal so this needs to get removed altogether.

2022-10-03 22:29 UTC, peachbits commented on src/components/modals/WalletListModal.tsx
> +  allowedWalletIds?: string[]
Will be deleted as it wasn't actually used

2022-10-03 22:31 UTC, peachbits commented on src/components/themed/WalletListSwipeable.tsx
> +      const { currencyCode, displayName } = item
Create wallet rows don't have names. Instead, I added the ability to search the pluginId as well and broke it out into a helper function (this was copy/pasted from another scene) in an additional commit

2022-10-03 22:51 UTC, paullinator approved these changes

2022-10-04 00:10 UTC, peachbits commented
/rebase

2022-10-04 00:44 UTC, merged