Sam/aave fee swap
EdgeApp/edge-react-gui pull request #3689
Opened 2022-09-30 04:36 UTC by samholmes

#### PR Dependencies

 none

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2022-10-07 01:42 UTC, Jon-edge requested changes

2022-10-07 01:42 UTC, Jon-edge commented on src/hooks/useAsyncValue.ts
> +  const [value, setValue] = React.useState<T | undefined>(undefined)
That's pretty neat, didn't know that!

2022-10-07 01:49 UTC, Jon-edge requested changes

2022-10-07 01:49 UTC, Jon-edge commented on src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
> +    const borrowWalletNativeBalance = borrowEngineWallet.balances[borrowEngineWallet.currencyInfo.currencyCode]
use useWalletBalance hook?

2022-10-07 01:50 UTC, Jon-edge commented
Looks good, but I noticed that there's no updates to the Loan Status display. Can we simply concatenate the display messages of the parallel actions for now? LoanStatusScene looks weird right now if you test it

2022-10-07 01:50 UTC, Jon-edge reviewed
Looks good, but I noticed that there's no updates to the Loan Status display. Can we simply concatenate the display messages of the parallel actions for now? LoanStatusScene looks weird right now if you test it

2022-10-07 01:51 UTC, Jon-edge requested changes
Looks good, but I noticed that there's no updates to the Loan Status display. Can we simply concatenate the display messages of the parallel actions for now? LoanStatusScene looks weird right now if you test it

2022-10-07 19:52 UTC, samholmes commented on src/hooks/useAsyncValue.ts
> +  const [value, setValue] = React.useState<T | undefined>(undefined)
👍

2022-10-07 22:37 UTC, samholmes commented on src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
> +    const borrowWalletNativeBalance = borrowEngineWallet.balances[borrowEngineWallet.currencyInfo.currencyCode]
You can't use hooks within callbacks.

2022-10-08 00:06 UTC, Jon-edge approved these changes
Approved after comments as discussed in our call:
-Would be nice to begin hiding away more implementations of things like fee calculations below of the GUI layer
-Update the dependencies for acf1fda30ea3d900675d479650a358fe94b6db0f to watch for wallet balances balances

2022-10-08 00:44 UTC, merged