Jon/aave/fix/swapuz-to-from-quote
EdgeApp/edge-react-gui pull request #3768
Opened 2022-10-29 19:54 UTC by Jon-edge

#### PR Dependencies

 none

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2022-11-01 01:11 UTC, samholmes approved these changes
Here's the changes

2022-11-01 01:11 UTC, samholmes commented on src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
> +  polygon: '1' // Min swap amounts for fees will always be > required fees
This should be `1.5` for polygon

2022-11-01 01:11 UTC, samholmes commented on src/components/scenes/Loans/LoanCreateScene.tsx
> +    totalRequiredCollateralNativeAmount = max(requiredSwapInputNativeAmount, minSwapInputNativeAmount)
Multiply by the rate to convert the units back.

2022-11-02 17:44 UTC, samholmes commented
/autosquash

2022-11-02 18:11 UTC, samholmes requested changes

2022-11-02 18:13 UTC, Jon-edge commented on src/components/cards/FiatAmountInputCard.tsx
> +  }, [allTokens, destToFiatRate, fiatAmount, nativeCryptoAmount, onAmountChanged, tokenId, wallet.currencyInfo])
It's a different nativeCryptoAmount. I can rename it

2022-11-02 18:18 UTC, Jon-edge commented on src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
> +  networkFeeAmount = isCrossChainSrc && gt(networkFeeAmount, borrowWalletNativeBalance) ? max(minFeeSwapAmount, networkFeeAmount) : networkFeeAmount
The right thing here is to pull all of this out of the scene to handle where it actually makes sense and it has context about what it needs to give these fee values

2022-11-02 20:06 UTC, merged