Fix localization on input for FiatAmountInputCard
EdgeApp/edge-react-gui pull request #3835
Opened 2022-12-02 22:10 UTC by Jon-edge

#### PR Dependencies

 none

#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2022-12-02 23:22 UTC, peachbits requested changes

2022-12-02 23:22 UTC, peachbits commented on src/components/cards/FiatAmountInputCard.tsx
> +    if (!zeroString(calculatedNativeCryptoAmount) && !zeroString(inputFiatAmount)) onAmountChanged(inputFiatAmount, calculatedNativeCryptoAmount)
This should be reverted so the (now) sanitized value is passed to `zeroString` and `onAmountChanged`. `zeroString` uses biggystring directly as well one of the parents of FiatAmountInputCard passes an `onAmountChanged` that eventually leads to biggystring.

2022-12-02 23:22 UTC, peachbits commented on src/components/cards/FiatAmountInputCard.tsx
> +          onAmountChanged(inputFiatAmount, nativeCryptoAmount)
Same issue here

2022-12-03 00:44 UTC, Jon-edge commented
Closing to open https://github.com/EdgeApp/edge-react-gui/pull/3838 with requested changes and a fixed branch name

2022-12-03 00:45 UTC, Jon-edge commented
Closing to open https://github.com/EdgeApp/edge-react-gui/pull/3838 with requested changes and a fixed branch name

2022-12-03 00:45 UTC, closed without merging