Add Optimism
EdgeApp/edge-react-gui pull request #4001
Opened 2023-02-15 03:01 UTC by peachbits

I thought it was important to allow OP to be splittable since it shares the same currency code with Ethereum. Since the splittable wallet list causes the wallet options modal to extend beyond small screens I went ahead and made it scrollable and unlocked the other splittable wallet types.

### Dependencies

https://github.com/EdgeApp/edge-currency-accountbased/pull/511
https://github.com/EdgeApp/edge-exchange-plugins/pull/262

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [ ] Tested on Android device
- [x] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203860831628486

2023-02-15 03:02 UTC, peachbits commented
https://user-images.githubusercontent.com/41451710/218916300-cfa85ba1-adb4-4849-9dd9-25602428e736.mp4

2023-02-16 21:10 UTC, swansontec requested changes
I noted one small change, but a bigger change is needed - on the side menu, the items slide smoothly under the gradient, fading out to blue. With your layout, the gradient doesn't fully cover the items, so they get cut off shaply.

2023-02-17 20:58 UTC, peachbits commented on src/components/modals/WalletListMenuModal.tsx
> +      <View style={styles.scrollViewContainer}>
I thought so too and I tried to use contentContainerStyle but no matter my config the modal always extended to the length of the screen. Using an additional View kept small lists contained to an appropriately small modal.

2023-02-17 22:09 UTC, peachbits commented
https://user-images.githubusercontent.com/41451710/219803182-8c6f163a-0ce0-40b0-8d88-cf73ea1464ab.mp4

2023-02-18 06:21 UTC, swansontec commented
/autosquash

2023-02-18 15:10 UTC, swansontec approved these changes

2023-02-18 15:10 UTC, swansontec commented on src/components/modals/WalletListMenuModal.tsx
> +    paddingBottom: theme.rem(3)
I changed the bottom padding to 3 rem, because the last item wasn't tappable.

2023-02-18 15:10 UTC, swansontec commented
- added: Add Optimism chain.

2023-02-18 15:17 UTC, merged