Replace all `FlatList`s with `FlashList`
EdgeApp/edge-react-gui pull request #4018
Opened 2023-02-20 23:18 UTC by itayplav

### CHANGELOG

### Dependencies

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [ ] Tested on Android device
- [x] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2023-02-23 22:56 UTC, swansontec requested changes

2023-02-23 22:56 UTC, swansontec commented on src/components/modals/AddressModal.tsx
> +              estimatedItemSize={72}
Please use `theme.rem(4.25)` for this, as all our sizes depend on that scale factor. Most of our rows use a standard height, like 3 or 4 rem, which you can determine from the row component itself.

2023-02-23 22:56 UTC, swansontec commented on src/components/modals/CategoryModal.tsx
> +            estimatedItemSize={51}
`THEME.rem(3)`, since it's the legacy theme in this modal.

2023-02-23 22:56 UTC, swansontec commented on src/components/modals/CategoryModal.tsx
> +            contentContainerStyle={styles.resultList}
The top border is part of this CSS. Putting it on the scrolling content container will mean that the border scrolls away, which we probably don't want.

2023-02-23 22:56 UTC, swansontec commented on src/components/modals/ListModal.tsx
> +        estimatedItemSize={86}
theme.rem(5)

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/CoinRankingScene.tsx
> +      <FlashList estimatedItemSize={64} data={listdata} renderItem={renderItem} onEndReachedThreshold={1} onEndReached={handleEndReached} />
theme.rem(3.75)

2023-02-23 22:56 UTC, swansontec commented on src/components/modals/WalletListModal.tsx
> +        <FlashList
No size estimate on this guy? His buddy has one in the same file.

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/CreateWalletCompletionScene.tsx
> -
Put back blank line here.

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/CreateWalletSelectCryptoScene.tsx
> -
Put back blank line here.

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/CreateWalletCompletionScene.tsx
> +            estimatedItemSize={72}
theme.rem(4.25)

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/CreateWalletSelectCryptoScene.tsx
> +            estimatedItemSize={72}
theme.rem(4.25)

2023-02-23 22:56 UTC, swansontec commented on src/components/modals/WalletListModal.tsx
> +          estimatedItemSize={72}
theme.rem(4.25)

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/CreateWalletSelectFiatScene.tsx
> -
Put back blank line.

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/DefaultFiatSettingScene.tsx
> +              estimatedItemSize={30}
theme.rem(1.75)

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/DefaultFiatSettingScene.tsx
> -
Put back blank line.

2023-02-23 22:56 UTC, swansontec commented on src/components/scenes/ManageTokensScene.tsx
> +      <FlashList data={filteredTokenIds} extraData={extraData} keyExtractor={keyExtractor} renderItem={renderRow} style={styles.tokenList} />
theme.rem(4.25) here.

2023-02-23 22:56 UTC, swansontec commented on src/components/themed/WalletList.tsx
> -
Put back blank line here.

2023-02-23 22:56 UTC, swansontec commented on src/components/themed/WalletList.tsx
> +    <FlashList data={walletList} keyboardShouldPersistTaps="handled" renderItem={renderRow} style={margin} />
theme.rem(4.25) here.

2023-02-23 22:56 UTC, swansontec commented on src/components/themed/WalletListSwipeable.tsx
> -
Put back blank line here.

2023-02-23 22:56 UTC, swansontec commented on src/components/themed/WalletListSwipeable.tsx
> +      estimatedItemSize={72}
theme.rem(4.25)

2023-02-23 22:56 UTC, swansontec commented on src/modules/FioAddress/components/ConnectWallets.tsx
> +                estimatedItemSize={72}
theme.rem(4.25)

2023-02-23 22:56 UTC, swansontec commented on src/modules/FioAddress/components/DomainListModal.tsx
> +        <FlashList data={items} estimatedItemSize={60} keyboardShouldPersistTaps="handled" keyExtractor={this.keyExtractor} renderItem={this.renderItem} />
theme.rem(3.5)

2023-02-23 22:56 UTC, swansontec commented on yarn.lock
> +prop-types@15.8.1:
Please run `yarn-deduplicate` in this repo.

2023-02-25 07:03 UTC, itayplav commented
> Please run `yarn-deduplicate` in this repo. 

Done

2023-02-25 07:05 UTC, itayplav commented
> No size estimate on this guy? His buddy has one in the same file. 

Added the same `estimatedItemSize={theme.rem(4.25)}` :)

2023-03-03 23:21 UTC, swansontec approved these changes

2023-03-04 01:13 UTC, merged