Tweak currency wallet error handling
EdgeApp/edge-react-gui pull request #4044
Opened 2023-03-06 22:24 UTC by peachbits

1) Show errors when creating wallets fails in account creation and when creating a single wallet
2) Show an error row when loading wallet fails

2023-03-06 22:25 UTC, peachbits commented
![Screen Shot 2023-03-06 at 2 22 10 PM](https://user-images.githubusercontent.com/41451710/223257966-f7d3912b-0b85-4752-9d82-d83017f5b306.png)

2023-03-07 17:56 UTC, swansontec requested changes
Just fix the `useWatch` thing, and maybe Michael can add a task to a future sprint if he cares deeply about the visuals.

2023-03-07 17:56 UTC, swansontec commented on src/components/themed/WalletListErrorRow.tsx
> +    </TouchableOpacity>
I think we upgrade the visuals later, such as adding the `CryptoIcon` for the wallet, but for now this is sooo much better.

2023-03-08 05:21 UTC, swansontec approved these changes

2023-03-08 09:45 UTC, merged