Upgrade cleaners
EdgeApp/edge-react-gui pull request #4140
Opened 2023-04-20 01:12 UTC by swansontec

### CHANGELOG

 none

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2023-04-20 23:24 UTC, peachbits requested changes

2023-04-20 23:24 UTC, peachbits commented on src/actions/ExchangeInfoActions.ts
> +        () => ({ source: [], destination: [] })
buy and sell also have default values

2023-04-21 07:22 UTC, ankit-gautam23 reviewed
Buy and sell should be associated with some default value.

2023-04-21 21:58 UTC, peachbits approved these changes

2023-04-21 22:31 UTC, merged