Maestro bootstrap shell script & `docs/MAESTRO.md`
EdgeApp/edge-react-gui pull request #4175
Opened 2023-05-08 23:41 UTC by itayplav

### Dependencies

none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2023-05-10 18:40 UTC, itayplav commented on docs/MAESTRO.md
> +/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/EdgeApp/edge-react-gui/maestro.sh)"
Note for reviewers: this command will not work until this PR has been merged - until then the correct command is:

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/EdgeApp/edge-react-gui/itay/maestro/readme/maestro.sh)"
```

2023-05-19 23:06 UTC, paullinator requested changes

2023-05-20 01:04 UTC, paullinator approved these changes
Approved with my fixup commit.

2023-05-20 04:35 UTC, merged

2023-05-20 11:58 UTC, itayplav commented on maestro.sh
> +EDGE_REACT_GUI_REPO_URL="https://github.com/EdgeApp/edge-react-gui"
I think your saying new repo ?

2023-05-20 12:20 UTC, itayplav commented on maestro.sh
> +exec $SHELL -l
vestigial sanity check to have an actual brand new shell..woops!