Add `runMaestro.ts` script
EdgeApp/edge-react-gui pull request #4206
Opened 2023-05-23 04:18 UTC by itayplav

### CHANGELOG

 none

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2023-05-26 00:05 UTC, paullinator requested changes
This could be simplified and less error prone by

1. Using clipanion
2. Break up the test specification like so

```
yarn maestro --tests [groupId]:[tagId],[groupIdOnly] --testNum 300-400,500-600 --skipTests [groupId] --skipNum 300,500-513
```

2023-05-30 02:28 UTC, itayplav commented on scripts/runMaestro.ts
> +      await runMaestro({ ...options, includedTests: '0:200913' })
Yep this was arbitrary - v2 uses the [catch all](https://github.com/EdgeApp/edge-react-gui/pull/4206/commits/b2fbe701fa13a91e6f6047a72144322645ca317a#diff-857a35d1cacd08cfc4c49807a5589e430cf880c0ecdef0b65dab379e5aa176efR176) test selector when no arguments are specified i.e. `yarn maestro`

2023-05-30 02:29 UTC, itayplav commented on scripts/runMaestro.ts
> +class Maestro {
Class structure has been replaced w/ loose functions

2023-05-30 02:30 UTC, itayplav commented on scripts/runMaestro.ts
> +    ${green}yarn maestro :login${reset}
This was an error in the documentation - now an empty string before/after a `:` is invalid, and at minimum requires a wildcard i.e. 

`+:2fa` -> all groups with the 2fa tag
`login:+` -> all tests in the login group

2023-05-30 02:32 UTC, itayplav commented on scripts/runMaestro.ts
> +    includedTests: args[0] ?? '',
Now uses [cac](https://github.com/cacjs/cac) for argument parsing

2023-06-23 03:18 UTC, paullinator approved these changes

2023-06-23 03:55 UTC, merged