Add metadata to migrate wallet transactions
EdgeApp/edge-react-gui pull request #4313
Opened 2023-07-05 21:25 UTC by peachbits

2023-07-05 21:25 UTC, peachbits commented
![Simulator Screen Shot - iPod touch (7th generation) - 2023-07-05 at 14 20 20](https://github.com/EdgeApp/edge-react-gui/assets/41451710/347b5aea-7b63-4ab5-8aba-289098c3274e)
![Simulator Screen Shot - iPod touch (7th generation) - 2023-07-05 at 14 20 15](https://github.com/EdgeApp/edge-react-gui/assets/41451710/fc9eb2f8-6bff-4b56-b233-7408692d6643)

2023-07-05 22:51 UTC, swansontec requested changes
I think we should fill in even more metadata, besides just notes.

2023-07-05 22:51 UTC, swansontec commented on src/components/scenes/MigrateWalletCompletionScene.tsx
> +            },
Can we do `category: "Transfer"` here? Also, Maybe put the wallet name also as `name: getWalletName(newWallet)`?

2023-07-06 18:52 UTC, peachbits commented
![migrate](https://github.com/EdgeApp/edge-react-gui/assets/41451710/a9d041e8-8f31-4050-9970-906e607facc2)

2023-07-07 17:45 UTC, swansontec requested changes

2023-07-07 17:45 UTC, swansontec commented on src/components/scenes/MigrateWalletCompletionScene.tsx
> +              category: 'transfer',
It needs to be `'Transfer'`, uppercase. We have always capitalized this, since the Airbitz days.

2023-07-11 17:02 UTC, swansontec approved these changes

2023-07-11 17:41 UTC, merged