Rewrite EOS handle scene
EdgeApp/edge-react-gui pull request #4352
Opened 2023-07-21 21:50 UTC by swansontec

### CHANGELOG

- changed: Re-theme the EOS handle scene.

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2023-07-21 21:56 UTC, swansontec commented
![simulator_screenshot_60BB7A33-BB02-4631-9260-AFA9E3B32A45](https://github.com/EdgeApp/edge-react-gui/assets/276214/67620718-ba32-42d3-bce4-3bc12010146d)
![simulator_screenshot_A9DCD6A7-62EE-4B67-9D38-A71ACF9B096F](https://github.com/EdgeApp/edge-react-gui/assets/276214/7894472f-f4f7-431b-9455-ba929bfcb15f)

2023-07-21 21:56 UTC, swansontec commented
![simulator_screenshot_8B8A596F-CA12-4317-9B43-22ED23BF9A09](https://github.com/EdgeApp/edge-react-gui/assets/276214/0e3e8613-f6b9-4952-b5f0-4c6cd5f5f445)
![simulator_screenshot_C1DA52EA-659B-4879-9110-9955320E2980](https://github.com/EdgeApp/edge-react-gui/assets/276214/740863ee-8982-424c-9e89-fc1d7a47364a)

2023-07-24 18:37 UTC, Jon-edge requested changes

2023-07-24 18:37 UTC, Jon-edge commented on src/components/scenes/CreateWalletAccountSetupScene.tsx
> +      <View style={{ paddingBottom: 400 }} />
This hard-coded padding allows you to scroll the scene for no reason, especially apparent when the keyboard is collapsed.

The MainButton ought to be stuck to the bottom of the screen or top of the keyboard.

2023-07-24 18:43 UTC, Jon-edge requested changes

2023-07-24 18:43 UTC, Jon-edge commented on src/components/scenes/CreateWalletAccountSetupScene.tsx
> +      />
Add `maxLength={12}` counter

2023-07-24 18:43 UTC, Jon-edge commented on src/components/scenes/CreateWalletAccountSetupScene.tsx
> +        disabled={spinning}
No reason to let the user continue if it didn't at least satisfy the 12 char requirement

2023-07-24 23:03 UTC, Jon-edge commented on src/components/scenes/CreateWalletAccountSetupScene.tsx
> +      <View style={{ paddingBottom: 400 }} />
However, this isn't possible unless we 
1. Disable scroll in the SceneWrapper or
2. Implement content size aware (dynamic scroll enable/disable) SceneWrapper or
3. Some other trick I never figured out

I'm fine punting this detail until we do 2

2023-07-24 23:17 UTC, Jon-edge approved these changes

2023-07-25 16:03 UTC, merged