Transparent Header/Tab Bar
EdgeApp/edge-react-gui pull request #4648
Opened 2023-12-22 01:18 UTC by samholmes

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-01-01 18:01 UTC, swansontec requested changes

2024-01-01 18:01 UTC, swansontec commented on src/theme/variables/edgeDark.ts
> +  headerBackground: [`#000000`, `#00000000`],
Do we have these in the palette? The second one could probably be `transparent`. Otherwise, use regular quotes instead of backtick quotes.

2024-01-02 20:15 UTC, samholmes commented on src/components/common/SceneWrapper.tsx
>    // to changes in the gap.
Document the contract change

2024-01-03 00:13 UTC, samholmes commented on src/components/Main.tsx
> +  return legacyLanding == null ? null : (
See https://github.com/EdgeApp/edge-react-gui/pull/4648/commits/2d212cf8a78e63ed9eb1c870474f05b488681056 and https://github.com/EdgeApp/edge-react-gui/pull/4648/commits/36b8bebb1794d6b12e3dfbedb3baa2aa2fa7f27a

2024-01-04 17:35 UTC, swansontec approved these changes

2024-01-04 17:38 UTC, swansontec approved these changes

2024-01-04 17:38 UTC, swansontec commented on src/components/common/SceneWrapper.tsx
> + * padding needing to avoid the safe area inset and header/tab-bar/etc.
s/needing/needed/

2024-01-04 22:16 UTC, merged