Light Account: Block Buy/Sell/Receive
EdgeApp/edge-react-gui pull request #4661
Opened 2023-12-29 03:03 UTC by Jon-edge

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [x] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2023-12-29 22:00 UTC, swansontec requested changes
Tiny spacing change is needed. I feel like support will beg us for the call-to-action if we don't add it ourselves, but we can put this if needed.

2023-12-29 22:45 UTC, Jon-edge commented on src/components/modals/BackupForTransferModal.tsx
> +  )
Major oops

2023-12-30 05:37 UTC, Jon-edge commented on src/components/modals/BackupForTransferModal.tsx
> +  )
Added a quick CTA, I'm also betting that we will come back to redesign this to align with the existing backup modal so I'm not doing anything too fancy.

2023-12-30 05:38 UTC, Jon-edge commented
I couldn't figure out how to refactor this modal into an action like in `BackupModalActions` since `NavigationBase` doesn't work

2024-01-02 00:01 UTC, swansontec approved these changes

2024-01-02 00:27 UTC, merged