Update FIO handle modal
EdgeApp/edge-react-gui pull request #4674
Opened 2024-01-03 03:04 UTC by Jon-edge

- Use ButtonsViewUi4
- Change green word highlight location

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [x] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [x] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-01-06 10:15 UTC, paullinator approved these changes

2024-01-06 10:16 UTC, paullinator requested changes
Where did you change the images?

2024-01-08 18:53 UTC, Jon-edge commented
> Where did you change the images?

From the spec:
![image](https://github.com/EdgeApp/edge-react-gui/assets/90650827/2dd64ebb-d21e-4822-9da7-48b60c432e78)

2024-01-08 23:35 UTC, paullinator commented
Per discussion. Change the image name so UI3 users get the same image as before and make UI4 images have a different name.

2024-01-09 04:19 UTC, paullinator approved these changes

2024-01-10 03:02 UTC, merged