Paul/tweak blur
EdgeApp/edge-react-gui pull request #4709
Opened 2024-01-12 08:45 UTC by paullinator

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-01-12 08:46 UTC, paullinator commented
<img width="479" alt="Screenshot 2024-01-12 at 00 45 16" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/9f9ded5e-e82b-401b-bf32-14b2e48d3c4a">
<img width="447" alt="Screenshot 2024-01-12 at 00 43 29" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/3c7e9271-5a7a-4442-8ffd-27035e24f90c">
<img width="890" alt="Screenshot 2024-01-12 at 00 42 52" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/7c3c294c-da62-43a3-bee0-481830d02734">
<img width="885" alt="Screenshot 2024-01-12 at 00 42 31" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/b9f9f56e-6281-4843-a2c1-528c34a8211a">

2024-01-13 22:26 UTC, paullinator commented
<img width="795" alt="Screenshot 2024-01-13 at 14 03 20" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/65402b9b-7285-4388-ad6e-0abff476a64f">
<img width="803" alt="Screenshot 2024-01-13 at 14 04 46" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/689dc20b-6568-40c2-8492-8b6ab7d09b9f">
<img width="787" alt="Screenshot 2024-01-13 at 14 05 02" src="https://github.com/EdgeApp/edge-react-gui/assets/6079354/4bcbbce4-31e3-4ef6-a02a-f5f33fbc643e">

2024-01-15 21:49 UTC, Jon-edge requested changes

2024-01-15 21:49 UTC, Jon-edge commented on src/types/Theme.ts
Remove Ui4 from keys
https://app.asana.com/0/1200382638405084/1206315466361658/f

2024-01-15 21:49 UTC, Jon-edge commented on src/components/ui4/ModalUi4.tsx
I noticed discrepancies between Android and iOS screens. Can we add cases to make it consistent? I noticed that only thing here specific to Android is the `BlurView`'s `overlayColor`, and we can probably make it look more consistent if we case out `modalBackgroundUi4`

2024-01-15 22:26 UTC, Jon-edge approved these changes

2024-01-15 23:23 UTC, merged