Paul/kado
EdgeApp/edge-react-gui pull request #4832
Opened 2024-02-08 06:12 UTC by paullinator

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-02-09 23:01 UTC, swansontec requested changes

2024-02-11 04:23 UTC, paullinator commented on src/plugins/gui/providers/kadoProvider.ts
> +                  const tokenId = asset.address.toLowerCase().replace('0x', '')
Already done in a new commit that addresses breaking API changes from Kado

2024-02-11 04:37 UTC, paullinator commented on src/plugins/gui/providers/kadoProvider.ts
> +                        await showUi.showError(new Error(lstrings.fiat_plugin_sell_failed_try_again + '\n\norderInfo.success=false'))
Unfortunately, the `showUi.showError` API isn't exactly the same as showError. That would require a bit of a refactor which I would agree with but would rather do as another commit/PR.

2024-02-11 04:38 UTC, paullinator commented on src/components/ui4/FiatExchangeDetailsCard.tsx
> +  useAsyncEffect(
I wasn't aware of `useAsyncValue` but good to know. I do like that `useAsyncEffect` allows a tag to help find crashes.

2024-02-11 04:48 UTC, paullinator commented
Please check the fixups AND the last two commits which were added since the first review

2024-02-11 16:08 UTC, swansontec approved these changes

2024-02-11 22:07 UTC, paullinator commented
/rebase

2024-02-11 22:20 UTC, merged