Paul/state picker
EdgeApp/edge-react-gui pull request #4854
Opened 2024-02-18 06:15 UTC by paullinator

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-02-23 06:07 UTC, Jon-edge requested changes
Minor changes

2024-02-23 06:07 UTC, Jon-edge commented on src/locales/en_US.ts
> +  error_must_select_state_province: 'Must select state/province for %s',
Needs to follow explicit _1s %1$s convention

2024-02-26 20:07 UTC, samholmes requested changes
One more change request about the use of `useHandler`. Otherwise, looks good to me.

2024-02-27 01:17 UTC, paullinator commented
/rebase

2024-02-27 02:15 UTC, merged