Fund New Account (Initial Impl)
EdgeApp/edge-react-gui pull request #4868
Opened 2024-02-23 01:36 UTC by Jon-edge

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [x] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-02-23 03:22 UTC, paullinator requested changes

2024-02-23 03:29 UTC, paullinator requested changes

2024-02-23 03:29 UTC, paullinator commented on src/components/modals/FundAccountModal.tsx
> +  )
This really should have an OK button to close the modal. Looks weird with no button.

2024-02-23 23:48 UTC, Jon-edge commented on src/components/ui4/PromoCardUi4.tsx
> +  const { localeMessages, ctaButton, background, dismissable } = promoInfo
I think the api is easier to understand for non-engineers on the info server if we just use "dismissable."

The info server already will clean this to default to true, but I can also add a default here

2024-02-24 02:26 UTC, paullinator requested changes
Buy/Sell list still needs to block light account users from tapping a payment method

2024-02-24 02:31 UTC, paullinator approved these changes

2024-02-26 04:46 UTC, paullinator commented
/rebase

2024-02-26 06:23 UTC, merged