Add a pw reminder notification
EdgeApp/edge-react-gui pull request #4877
Opened 2024-02-27 23:54 UTC by Jon-edge

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-02-28 22:38 UTC, swansontec requested changes
This looks good, but there is some dead code leftover.

2024-02-28 22:38 UTC, swansontec commented on src/components/services/Services.tsx
> +      if (account != null) {
Delete `needsPasswordCheck` from the list below, and then delete the selector above, as this is no longer needed.

2024-02-29 00:55 UTC, Jon-edge commented
Also had a flipped logic bug in the notification visibility

2024-02-29 04:33 UTC, swansontec approved these changes

2024-02-29 21:48 UTC, merged