Block Light Account Plugin Deeplinks
EdgeApp/edge-react-gui pull request #4889
Opened 2024-03-06 02:02 UTC by Jon-edge

Audit deeplinks:
- 'paymentProto' - Simply routes to send scene. User flow after that already blocks light accounts.
- 

Disallow deeplinks:
- Request for Address Links
- fiatPlugin - openWebView, openExternalWebView

- Improve backup modal ergonomics

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-03-10 16:25 UTC, paullinator requested changes

2024-03-10 16:25 UTC, paullinator commented on src/plugins/gui/scenes/FiatPluginWebView.tsx
> +  const { route, navigation } = props
changing this file is unnecessary. This is only launched after we've launched a fiatPlugin which is already blocked

2024-03-10 16:25 UTC, paullinator commented on src/actions/ScanActions.tsx
> +  if (checkAndShowLightBackupModal(account, navigation)) return await Promise.resolve()
just return. no need for `await Promise.resolve()`

2024-03-11 23:04 UTC, Jon-edge commented on src/components/modals/TransferModal.tsx
> +    if (checkAndShowLightBackupModal(account, navigation)) {
Per your comment in the GuiPluginListScene, we're only restricting buys there...

2024-03-11 23:43 UTC, paullinator approved these changes

2024-03-11 23:46 UTC, paullinator approved these changes

2024-03-12 00:06 UTC, merged