Jon/fix/balance-loading
EdgeApp/edge-react-gui pull request #5108
Opened 2024-06-21 00:19 UTC by Jon-edge

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [x] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-06-24 17:39 UTC, swansontec requested changes

2024-06-24 17:39 UTC, swansontec commented on src/components/ui4/BalanceCardUi4.tsx
> +  )
I don't think we need `useAsyncEffect` here. Instead, we can consolidate the `exchangeRatesReady` logic with the `isWalletsLoaded` logic into a single loop:

```ts
const activeWalletIds = useWatch(account, 'activeWalletIds')
const currencyWallets = useWatch(account, 'currencyWallets')
const currencyWalletErrors = useWatch(account, 'currencyWalletErrors')

const exchangeRatesReady = React.useMemo(() =>
  activeWalletIds.every(walletId => {
    // Ignore wallets that have crashed:
    if (currencyWalletErrors[walletId]) return true

    // Both the wallet and its rate need to be loaded:
    const wallet = currencyWallets[walletId]
    return wallet != null && exchangeRates[`${wallet.currencyInfo.currencyCode}_${defaultIsoFiat}`] != null
  })
, [activeWalletIds, currencyWallets, currencyWalletErrors])
```

2024-06-24 17:39 UTC, swansontec commented on src/hooks/useAccountWalletsSyncProgress.tsx
> +  )
Don't use a memo here. The `useMemo` hook needs to loop over its dependency array to see if anything has changed, which is going to cost more than just re-doing the division on each run. Math is really fast.

2024-06-24 17:39 UTC, swansontec commented on src/hooks/useAccountWalletsSyncProgress.tsx
> +  )
Also, I request that this hook return a value in the range of 0-1, and have the name `useAccountSyncRatio`. That makes it clearer what the units are, and mirrors the fact that the wallets themselves operate on a 0-1 scale. Visual components like the sync bar can convert the range as necessary for display purposes (like 0% - 100%).

2024-06-25 06:15 UTC, paullinator commented
/rebase

2024-06-25 06:16 UTC, paullinator approved these changes

2024-06-25 06:20 UTC, merged