Add more zealot metadata
EdgeApp/edge-react-gui pull request #5202
Opened 2024-08-14 18:00 UTC by paullinator

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-08-14 22:46 UTC, samholmes requested changes
Mainly need clarity on the regex.

2024-08-14 22:46 UTC, samholmes commented on scripts/deploy.ts
> +    const changes = rmNewline(cmd(`git diff HEAD^ HEAD CHANGELOG.md | grep '^+[^+]'`))
Why is it only matching line removals and not line additions? I'm a little confused on what this regex does.

2024-08-17 00:51 UTC, paullinator commented on scripts/deploy.ts
> +    const changes = rmNewline(cmd(`git diff HEAD^ HEAD CHANGELOG.md | grep '^+[^+]'`))
It finds the line additions, not removals. the first ^+ matches the beginning of the line that starts with a `+`. the `[^+]` matches a second character which is anything but a `+`. This prevents matching the +++ at the top of a diff so the only lines that get matched start with a `+` followed by the line added which for our format always starts with a `-` such as `- added: some feature`.

2024-08-17 00:54 UTC, samholmes approved these changes

2024-08-17 00:55 UTC, samholmes commented on scripts/deploy.ts
> +    const changes = rmNewline(cmd(`git diff HEAD^ HEAD CHANGELOG.md | grep '^+[^+]'`))
Wait, shouldn’t it be ^\+ then?

2024-08-17 01:13 UTC, merged