Change assetStatusCards to the new assetStatusCards2 from info server
EdgeApp/edge-react-gui pull request #5239
Opened 2024-09-09 23:55 UTC by Jon-edge

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [x] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2024-09-12 18:56 UTC, swansontec approved these changes

2024-09-12 23:55 UTC, paullinator requested changes
Do not merge. This PR is completely misses the spec of the task

2024-09-17 16:01 UTC, paullinator requested changes
Added a fixup but it's not tested. Please test and merge if it works

2024-09-17 16:44 UTC, Jon-edge commented on src/components/cards/InfoCardCarousel.tsx
> +export const InfoCardCarousel = (props: Props) => {
I saw the diff worked out, or else I would have separated the commits. Will
default to separating to be safe in the future

2024-09-17 16:45 UTC, Jon-edge commented on src/components/cards/InfoCardCarousel.tsx
> +  const { countryCode, navigation, screenWidth, cards = [] } = props
Didn't realize that can trigger an infinite loop. Tested behavior before and
after the fix and it checks out.

2024-09-17 17:10 UTC, merged