Jon/notification-scene
EdgeApp/edge-react-gui pull request #5339
Opened 2024-11-01 22:48 UTC by Jon-edge

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS device
- [ ] Tested on Android device
- [ ] Tested on small-screen device (iPod Touch)
- [ ] Tested on large-screen device (tablet)

2025-01-24 18:56 UTC, swansontec requested changes

2025-01-24 18:56 UTC, swansontec commented on src/components/icons/IconBadge.tsx
> +  const incompleteNotifs = Object.values(notifState).filter(notifInfo => !notifInfo.isCompleted).length
We shouldn't be mixing business logic with display logic. Please pull this logic out to the notification scene / side menu button, and instead take a prop like `count?: number` here in the badge component.

If you want, you could create a `useNotificationCount` hook to return the number derived here, to make life easier in those other places.

2025-01-24 22:40 UTC, Jon-edge commented on src/actions/LocalSettingsActions.tsx
> + * @deprecated Can probably remove this
We use this to ensure we only show `ip2FaNotifShown` once. I can just use
`writeLocalAccountSettings` for this now that I think about it.

2025-01-27 19:09 UTC, swansontec requested changes

2025-01-27 19:09 UTC, swansontec commented on src/components/scenes/NotificationCenterScene.tsx
> +    .sort((a, b) => notifState[b].dateReceived.getMilliseconds() - notifState[a].dateReceived.getMilliseconds())
Please use `Date.valueOf`, which returns the same sort of value as `Date.now`.

The `getMilliseconds` doesn't do what you think it does. In a date like `2025-01-01T02:03:04.345`, the `getMilliseconds` would return "345", which is just the decimal part of the seconds. So it's not very useful.

2025-01-27 19:09 UTC, swansontec commented on src/components/themed/SideMenu.tsx
> +  console.debug(number)
Leftover debugging.

2025-01-27 19:09 UTC, swansontec commented on src/components/scenes/NotificationCenterScene.tsx
> +    .sort((a, b) => notifState[b].dateReceived.getMilliseconds() - notifState[a].dateReceived.getMilliseconds())
`Date.valueOf`

2025-01-27 19:09 UTC, swansontec commented on src/actions/LocalSettingsActions.ts
> +export function useNotifNumber(): number | undefined {
I would call this `useNotifCount`, since it's the number pending notifications.

2025-01-28 18:57 UTC, swansontec approved these changes

2025-01-28 19:03 UTC, swansontec commented on src/types/types.ts
> +}
Did it myself

2025-01-29 07:14 UTC, merged